video_processing:
  src_corners: [[892, 616], [564, 674], [1733, 826], [1705, 714]]
  scale: 0.75
  crop_top_ratio: 0
  crop_side_ratio: 0
  buffer_size: 5 # number of frames to buffer

stopsign_detection:
  stopsign_line: [[650, 450], [500, 500]]
  stop_box_tolerance: 50 # pixels
  min_stop_duration: 2  # seconds
  movement_allowance: 1  # pixels / second
  frames_before_parked: 30

tracking:
  use_kf: true

output:
  save_video: true

debugging_visualization:
  draw_grid: true
  grid_increment: 100

stream_settings:
  fps: 15
  vehicle_classes: [1, 2, 3, 5, 6, 7]