video_processing:
  scale: 0.75
  crop_top: 0
  crop_side: 0
  frame_buffer_size: 500 # number of frames to buffer

stopsign_detection:
  stop_line: [[600, 500], [500, 600]]
  stop_box_tolerance: [50, 50]
  pre_stop_zone: [750, 800]
  image_capture_zone: [800, 900]
  max_movement_speed: 20  # pixels / second
  parked_frame_threshold: 60
  unparked_frame_threshold: 20
  in_zone_frame_threshold: 10
  out_zone_frame_threshold: 10
  stop_speed_threshold: 20

tracking:
  use_kalman_filter: true

output:
  save_video: true
  frame_skip: 3
  jpeg_quality: 10

debugging_visualization:
  draw_grid: true
  grid_size: 100

stream_settings:
  input_source: live
  fps: 15
  vehicle_classes: [1, 2, 3, 5, 6, 7]