video_processing:
  scale: 0.75
  crop_top: 0
  crop_side: 0
  frame_buffer_size: 5 # number of frames to buffer

stopsign_detection:
  stop_line: [[650, 450], [500, 500]]
  stop_box_tolerance: 50 # pixels
  min_stop_time: 2  # seconds
  max_movement_speed: 20  # pixels / second
  parked_frame_threshold: 60
  unparked_frame_threshold: 20

tracking:
  use_kalman_filter: true

output:
  save_video: true
  frame_skip: 3
  jpeg_quality: 10

debugging_visualization:
  draw_grid: true
  grid_size: 100

stream_settings:
  fps: 15
  vehicle_classes: [1, 2, 3, 5, 6, 7]