services:

  video_analyzer:
    build:
      context: .
      dockerfile: Dockerfile.processor
    env_file:
      - .env
    environment:
      REDIS_URL: ${REDIS_URL}
      PROMETHEUS_PORT: ${PROMETHEUS_PORT}
      RAW_FRAME_KEY: ${RAW_FRAME_KEY}
      PROCESSED_FRAME_KEY: ${PROCESSED_FRAME_KEY}
      YOLO_MODEL_NAME: ${YOLO_MODEL_NAME}
      DB_URL: ${DB_URL}
    volumes:
      - storage-dir:/app/data
    networks:
      - default
      - monitoring
      - coolify
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  ffmpeg_service:
    build:
      context: .
      dockerfile: Dockerfile.ffmpeg
    env_file:
      - .env
    environment:
      REDIS_URL: ${REDIS_URL}
      PROCESSED_FRAME_KEY: ${PROCESSED_FRAME_KEY}
    volumes:
      - storage-dir:/app/data
    depends_on:
      - video_analyzer
    networks:
      - default
      - monitoring
      - coolify
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
                - video

  web_server:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - ${WEB_SERVER_PORT}:8000
    env_file:
      - .env
    environment:
      DB_URL: ${DB_URL}
    depends_on:
      - video_analyzer
    volumes:
      - storage-dir:/app/data
    networks:
      - default
      - monitoring
      - coolify

networks:
  default:
  monitoring:
    name: monitoring
    external: true
  coolify:
    name: coolify
    external: true

volumes:
  storage-dir:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /gemini/data