services:

  video_analyzer:
    build:
      context: .
      dockerfile: Dockerfile.processor
    env_file:
      - .env
    environment:
      - YOLO_MODEL_PATH=/app/models/yolov8n.pt
      - PROMETHEUS_PORT=8002
      - CUDA_VISIBLE_DEVICES=1
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./stream:/app/stream
      - ./config.yaml:/app/config.yaml
      - ./stopsign:/app/stopsign
    expose:
      - 8002
    networks:
      - default
      - monitoring
      - coolify
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  ffmpeg_service:
    build:
      context: .
      dockerfile: Dockerfile.ffmpeg
    env_file:
      - .env
    volumes:
      - ./stream:/app/stream
      - ./stopsign:/app/stopsign
    depends_on:
      - video_analyzer
    networks:
      - default
      - monitoring
      - coolify

  web_server:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - video_analyzer
    volumes:
      - ./static:/app/static
      - ./data:/app/data
      - ./stream:/app/stream
      - ./config.yaml:/app/config.yaml
      - ./stopsign:/app/stopsign
    networks:
      - default
      - monitoring
      - coolify

networks:
  default:
  monitoring:
    name: monitoring
    external: true
  coolify:
    name: coolify
    external: true