services:

  stream_processor:
    build:
      context: .
      dockerfile: Dockerfile.processor
    env_file:
      - .env
    environment:
      - YOLO_MODEL_PATH=/app/models/yolov8n.pt
      - PROMETHEUS_PORT=8002
    volumes:
      - ./models:/app/models
      - ./config.yaml:/app/config.yaml
      - ./stopsign:/app/stopsign
    expose:
      - 8002
    networks:
      - default
      - monitoring
      - coolify

  web_server:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - stream_processor
    volumes:
      - ./static:/app/static
      - ./config.yaml:/app/config.yaml
      - ./stopsign:/app/stopsign
    networks:
      - default
      - monitoring
      - coolify

networks:
  default:
  monitoring:
    name: monitoring
    external: true
  coolify:
    name: coolify
    external: true