services:

  video_analyzer:
    build:
      context: .
      dockerfile: Dockerfile.processor
    env_file:
      - .env
    environment:
      - PROMETHEUS_PORT=${PROMETHEUS_PORT}
    volumes:
      - ${YOLO_MODEL_DIR}:/app/models
      - ${DATA_DIR}:/app/data
      - ${STREAM_DIR}:/app/stream
      - ./config.yaml:/app/config.yaml
    networks:
      - default
      - monitoring
      - coolify
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  ffmpeg_service:
    build:
      context: .
      dockerfile: Dockerfile.ffmpeg
    env_file:
      - .env
    volumes:
      - ./stream:/app/stream
    depends_on:
      - video_analyzer
    networks:
      - default
      - monitoring
      - coolify
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, video]

  web_server:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - ${WEB_SERVER_PORT}:8000
    env_file:
      - .env
    depends_on:
      - video_analyzer
    volumes:
      - ./static:/app/static
      - ${DATA_DIR}:/app/data
      - ${STREAM_DIR}:/app/stream
      - ./config.yaml:/app/config.yaml
    networks:
      - default
      - monitoring
      - coolify

networks:
  default:
  monitoring:
    name: monitoring
    external: true
  coolify:
    name: coolify
    external: true