services:

  stream_processor:
    build:
      context: .
      dockerfile: Dockerfile.processor
    env_file:
      - .env
    environment:
      - YOLO_MODEL_PATH=/app/models/yolov8n.pt
    volumes:
      - ./models:/app/models
      - ./config.yaml:/app/config.yaml

  web_server:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - stream_processor