# ffmpeg_service/Dockerfile.ffmpeg

FROM python:3.12-slim

# Install FFmpeg
RUN apt-get update && apt-get install -y ffmpeg && rm -rf /var/lib/apt/lists/*

# Install uv
RUN pip install uv

RUN pip install redis

# Set work directory
WORKDIR /app

# Copy project
COPY stopsign /app/stopsign

# Default command
CMD ["uv", "run", "python", "-m", "stopsign.ffmpeg_service"]