services:
  rtsp_to_redis:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../app:/app
    env_file:
      - ../.env
    environment:
      - PROMETHEUS_PORT=8001
    expose:
      - 8001
    networks:
      - default
      - monitoring
      - coolify

networks:
  default:
  monitoring:
    name: monitoring
    external: true
  coolify:
    name: coolify
    external: true