services:
  rtsp_to_redis:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../app:/app
    env_file:
      - ../.env

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
    ports:
      - "3000:3000"

volumes:
  grafana-storage:
  prometheus-data: