services:

  video_analyzer:
    build:
      context: ..
      dockerfile: docker/Dockerfile.processor
    env_file:
      - .env
    environment:
      REDIS_URL: ${REDIS_URL}
      PROMETHEUS_PORT: ${PROMETHEUS_PORT}
      RAW_FRAME_KEY: ${RAW_FRAME_KEY}
      PROCESSED_FRAME_KEY: ${PROCESSED_FRAME_KEY}
      YOLO_MODEL_NAME: ${YOLO_MODEL_NAME}
      DB_URL: ${DB_URL}
    networks:
      - default
      - monitoring
      - coolify
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "--max-time", "5", "http://localhost:${PROMETHEUS_PORT}/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3

  ffmpeg_service:
    build:
      context: ..
      dockerfile: docker/Dockerfile.ffmpeg
    env_file:
      - .env
    environment:
      REDIS_URL: ${REDIS_URL}
      PROCESSED_FRAME_KEY: ${PROCESSED_FRAME_KEY}
    volumes:
      - storage-dir:/app/data
    depends_on:
      - video_analyzer
    networks:
      - default
      - monitoring
      - coolify
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities:
                - gpu
                - video
    healthcheck:
      test: ["CMD", "curl", "-f", "--max-time", "5", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  web_server:
    build:
      context: ..
      dockerfile: docker/Dockerfile.web
    ports:
      - ${WEB_SERVER_PORT}:8000
    env_file:
      - .env
    environment:
      DB_URL: ${DB_URL}
    depends_on:
      - video_analyzer
    volumes:
      - storage-dir:/app/data
    networks:
      - default
      - monitoring
      - coolify
    healthcheck:
      test: ["CMD", "curl", "-f", "--max-time", "20", "http://localhost:8000/health"]
      interval: 60s
      timeout: 20s
      retries: 5
      start_period: 60s

networks:
  default:
  monitoring:
    name: monitoring
    external: true
  coolify:
    name: coolify
    external: true

volumes:
  storage-dir: